name: DBT Workflow

on:
  push:
    branches:
      - main

env:
  DBT_PROFILE_DIR: ${{ github.workspace }}/dbt/nba_dbt_project

jobs:
  setup_run_test_dbt:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dbt
      run: pip install dbt-postgres

    - name: Run dbt models
      run: dbt run --profiles-dir ${{ env.DBT_PROFILE_DIR }} --target dev
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
      working-directory: ./dbt/nba_dbt_project

    - name: Test dbt models
      run: dbt test --profiles-dir ${{ env.DBT_PROFILE_DIR }} --target dev
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
      working-directory: ./dbt/nba_dbt_project

