name: DBT CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  dbt_run_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Setup Dynamic profiles.yml
        run: |
          mkdir -p ./dbt/nba_dbt_project
          echo "nba_dbt_project:" > ./dbt/profiles.yml
          echo "  target: dev" >> ./dbt/profiles.yml
          echo "  outputs:" >> ./dbt/profiles.yml
          echo "    dev:" >> ./dbt/profiles.yml
          echo "      type: postgres" >> ./dbt/profiles.yml
          echo "      threads: 1" >> ./dbt/profiles.yml
          echo "      host: 192.168.11.238" >> ./dbt/profiles.yml
          echo "      port: 5432" >> ./dbt/profiles.yml
          echo "      user: '${{ secrets.DB_USER }}'" >> ./dbt/profiles.yml
          echo "      pass: '${{ secrets.DB_PASS }}'" >> ./dbt/profiles.yml
          echo "      dbname: '${{ secrets.DB_NAME }}'" >> ./dbt/profiles.yml
          echo "      schema: public" >> ./dbt/profiles.yml

      - name: Install dbt dependencies
        run: dbt deps
        working-directory: ./dbt/nba_dbt_project

      - name: Run dbt models
        run: dbt run --profiles-dir ../
        working-directory: ./dbt/nba_dbt_project

      - name: Test dbt models
        run: dbt test --profiles-dir ../
        working-directory: ./dbt/nba_dbt_project
