name: DBT Workflow

on:
  push:
    branches:
      - main

jobs:
  setup_run_test_dbt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Choose the Python version compatible with your dbt project

    - name: Install dbt
      run: pip install dbt-postgres # Install the appropriate dbt adapter

    - name: Create dbt profiles.yml
      run: |
        mkdir -p ~/.dbt
        echo "nba_dbt_project:" > ~/.dbt/profiles.yml
        echo "  outputs:" >> ~/.dbt/profiles.yml
        echo "    dev:" >> ~/.dbt/profiles.yml
        echo "      dbname: ${{ secrets.DB_NAME }}" >> ~/.dbt/profiles.yml
        echo "      host: localhost" >> ~/.dbt/profiles.yml
        echo "      pass: ${{ secrets.DB_PASS }}" >> ~/.dbt/profiles.yml
        echo "      port: 5432" >> ~/.dbt/profiles.yml
        echo "      schema: public" >> ~/.dbt/profiles.yml
        echo "      threads: 1" >> ~/.dbt/profiles.yml
        echo "      type: postgres" >> ~/.dbt/profiles.yml
        echo "      user: ${{ secrets.DB_USER }}" >> ~/.dbt/profiles.yml
        echo "  target: dev" >> ~/.dbt/profiles.yml

    - name: Run dbt models
      run: dbt run --profiles-dir ~/.dbt
      working-directory: ./path/to/your/dbt/project

    - name: Test dbt models
      run: dbt test --profiles-dir ~/.dbt
      working-directory: ./path/to/your/dbt/project

