name: DBT Actions

# Defines when the action will run. 
on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  dbt-run-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dbt
      run: pip install dbt-postgres

    - name: Setup dbt profiles.yml
      run: |
        mkdir -p ~/.dbt
        echo "nba_dbt_project:" > ~/.dbt/profiles.yml
        echo "  target: dev" >> ~/.dbt/profiles.yml
        echo "  outputs:" >> ~/.dbt/profiles.yml
        echo "    dev:" >> ~/.dbt/profiles.yml
        echo "      type: postgres" >> ~/.dbt/profiles.yml
        echo "      host: localhost" >> ~/.dbt/profiles.yml
        echo "      user: ${{ secrets.DB_USER }}" >> ~/.dbt/profiles.yml
        echo "      pass: ${{ secrets.DB_PASS }}" >> ~/.dbt/profiles.yml
        echo "      port: 5432" >> ~/.dbt/profiles.yml
        echo "      db: ${{ secrets.DB_NAME }}" >> ~/.dbt/profiles.yml
        echo "      schema: public" >> ~/.dbt/profiles.yml
        echo "      threads: 1" >> ~/.dbt/profiles.yml

    - name: Run dbt models
      run: |
        cd dbt/nba_dbt_project
        dbt run

    - name: Test dbt models
      run: |
        cd dbt/nba_dbt_project
        dbt test

